[package]
name = "pliron-circt"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/KwachOjunga/pliron-circt"
categories = ["compilers"]
keywords = ["pliron", "hardware", "circt", "compiler", "rtl"]
authors = ["Reginald Ojunga"]
description = "An MLIR-based compiler infrastructure spanning multiple abstraction levels of hardware representation, transformation, and RTL generation"
[features]
default = ["sv", "hw", "comb", "seq", "fsm"]
sv = []
hw = []
comb = []
seq = []
fsm = []

[dependencies]
pliron =  {git = "https://github.com/pliron-org/pliron", rev = "e66025a", version = "0.17.0"}
thiserror = "2"
log = { version = "0" }
rustc-hash = "2"
awint = "0"
sv-parser = { git = "https://github.com/KwachOjunga/sv-parser", version = "0.13.5" }

[dev-dependencies]
expect-test = "1"
env_logger = "0"
